"""
SQLMODEL INTEGRATION WITH SQLITE
================================
This script demonstrates how to integrate SQLModel (which combines SQLAlchemy & Pydantic)
with FastAPI to query and modify a SQLite database.
"""

from typing import Optional
from contextlib import asynccontextmanager
from fastapi import FastAPI, Depends, HTTPException, status
from sqlmodel import Field, Session, SQLModel, create_engine, select

# Define the SQLModel representing a Hero table in the database
# By setting table=True, this class maps to a database table as well as a Pydantic schema
class Hero(SQLModel, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    name: str = Field(index=True)
    secret_name: str
    age: Optional[int] = Field(default=None, index=True)

# Path to the SQLite database file
sqlite_file_name = "fastapi_heroes.db"
sqlite_url = f"sqlite:///{sqlite_file_name}"

# Engines handle connection pools to SQLite.
# connect_args={"check_same_thread": False} is required only for SQLite to allow multi-threaded access.
engine = create_engine(sqlite_url, connect_args={"check_same_thread": False})

# Lifespan context manager to create tables when the FastAPI app starts
@asynccontextmanager
async def lifespan(app: FastAPI):
    # Create all database tables (analogous to run migrations)
    SQLModel.metadata.create_all(engine)
    yield
    # Cleanup database (optional / here we leave the db file as is)

app = FastAPI(title="SQLModel CRUD API", lifespan=lifespan)

# Dependency to provide the DB Session.
# Yield ensures the session is closed automatically when the request completes.
def get_session():
    with Session(engine) as session:
        yield session

# 1. CREATE
@app.post("/heroes/", response_model=Hero, status_code=status.HTTP_201_CREATED)
def create_hero(hero: Hero, session: Session = Depends(get_session)):
    session.add(hero)
    session.commit()
    session.refresh(hero) # Populates the autogenerated 'id'
    return hero

# 2. READ ALL
@app.get("/heroes/", response_model=list[Hero])
def read_heroes(
    skip: int = 0, 
    limit: int = 100, 
    session: Session = Depends(get_session)
):
    heroes = session.exec(select(Hero).offset(skip).limit(limit)).all()
    return heroes

# 3. READ ONE
@app.get("/heroes/{hero_id}", response_model=Hero)
def read_hero(hero_id: int, session: Session = Depends(get_session)):
    hero = session.get(Hero, hero_id)
    if not hero:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND, 
            detail=f"Hero with ID {hero_id} not found."
        )
    return hero

# 4. UPDATE
@app.patch("/heroes/{hero_id}", response_model=Hero)
def update_hero(
    hero_id: int, 
    hero_update: Hero, 
    session: Session = Depends(get_session)
):
    hero = session.get(Hero, hero_id)
    if not hero:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND, 
            detail=f"Hero with ID {hero_id} not found."
        )
    
    # Extract request payload fields
    hero_data = hero_update.model_dump(exclude_unset=True)
    for key, value in hero_data.items():
        setattr(hero, key, value)
        
    session.add(hero)
    session.commit()
    session.refresh(hero)
    return hero

# 5. DELETE
@app.delete("/heroes/{hero_id}", status_code=status.HTTP_204_NO_CONTENT)
def delete_hero(hero_id: int, session: Session = Depends(get_session)):
    hero = session.get(Hero, hero_id)
    if not hero:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND, 
            detail=f"Hero with ID {hero_id} not found."
        )
    session.delete(hero)
    session.commit()
    return None

# To run this file:
# uvicorn 06_databases_and_orm.01_sqlmodel_sqlite:app --reload
