"""
API METADATA AND ROUTE DOCUMENTATION
====================================
This script demonstrates how to enrich the OpenAPI documentation generated by FastAPI.
You will learn to write docstrings, endpoint summaries, and custom description fields.
"""

from fastapi import FastAPI, status

app = FastAPI(title="Enriched Documentation API")

# Customizing Swagger UI tags and formatting
# - 'summary': short title in Swagger.
# - 'description': long-form text (supports Markdown).
# - 'tags': categories on UI.
@app.get(
    "/payments/",
    summary="Process customer transaction payment",
    description="""
    This endpoint executes a **secure charge** against a card token:
    - **Step 1:** Verifies the user account.
    - **Step 2:** Calls the external bank clearing gateway.
    - **Step 3:** Logs transaction success metadata.
    """,
    tags=["Financials"],
    status_code=status.HTTP_202_ACCEPTED
)
def process_payment(amount: float, currency: str = "USD"):
    # This description shows up in the Swagger documentation
    return {"status": "processing", "amount": amount, "currency": currency}


# Writing python docstrings inside route handler functions
# is automatically parsed by FastAPI as the endpoint's description.
@app.get("/system/health", tags=["Utilities"])
def check_health():
    """
    Check system vitals.
    
    Returns standard system health details, database connection status,
    and server uptime.
    """
    return {"status": "healthy", "database": "connected"}

# To run this file:
# uvicorn 07_advanced_routing.02_routing_tags:app --reload
